version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=expenses
      - POSTGRES_PASSWORD=expenses
      - POSTGRES_DB=expenses
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local