server.port: 10000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expenses
    driver-class-name: org.postgresql.Driver
    username: expenses
    password: expenses
  jpa:
    hibernate:
      ddl-auto: create-drop
    data:
      rest:
        base-path: /api